- hosts: localhost
  tasks:
    
    - name: enable verbose mode
      ini_file: dest=~/DockerConOpenstack/agent/config.cfg section=central-server option=ipaddr value="{{ ansible_default_ipv4.address}}" backup=yes
      tags: configuration 
    

    - name: Create the system service for flask server- Part1
      shell: 'sudo cp ~/DockerConOpenstack/Server/flask.conf /etc/init.d/'
        
    - name: Create the system service for flask server- Part2
      shell: 'sudo cp ~/DockerConOpenstack/Server/flask.service /lib/systemd/system/flask.service'

    - name: Install aptitude using apt
      become: yes
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      become: yes
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools','redis-server']
    
    - name: Installing flask_restful
      pip: 
        name: flask-restful
    
    - name: Installing redis-py
      pip: 
        name: redis
    
    - name: Installing inotify
      pip: 
        name: inotify
       
    - name: Installing Flask
      pip: 
        name: Flask
    - name: Change file ownership, group and permissions
      file: dest=~/DockerConOpenstack/Server/apiserver.py mode=a+x
      

    - name: Start service flask, if not started
      become: yes
      systemd:
        name: flask
        state: started


        
