- hosts: localhost
  tasks:

    - name: Create Server VM 
      os_server:
        state: present
        name: "Fog Server"
        image: "{{image}}"
        key_name: "{{key_name}}"
        flavor: "m2.tiny"
        network: "{{network}}"
        security_groups: default
        boot_from_volume: True
        volume_size: 20
        timeout: 200
      register: openstackmaster
     

    - name: Create temporary inventory for ssh wait
      add_host:
        name: "server"
        groups: vms, master
        ansible_host: "{{ openstackmaster.openstack.public_v4 }}"
        ansible_user: ubuntu
        ansible_ssh_common_args: > 
          -o BatchMode=yes
          -o UserKnownHostsFile=/dev/null
          -o StrictHostKeyChecking=no
    
    - name: enable verbose mode
      ini_file: dest=~/DockerConOpenstack/agent/config.cfg section=central-server option=ipaddr value="{{ openstackmaster.openstack.public_v4 }}" backup=yes
      tags: configuration 
    
    - name: Debug
      debug: 
        msg: "{{ openstackmaster.openstack.public_v4 }}"

- hosts: vms
  gather_facts: no
  
  tasks:
    - name: Wait for ssh to wake up
      wait_for_connection:
         timeout: 200
    - name: Copy project directory to the remote server
      remote_user: "ubuntu"
      copy:
        src: "{{src}}" 
        dest: "{{dest}}"
    
    - name: Create the system service for flask server- Part1
      shell: 'sudo cp ~/Server/flask.conf /etc/init.d/'
        
    - name: Create the system service for flask server- Part2
      shell: 'sudo cp ~/Server/flask.service /lib/systemd/system/flask.service'

    - name: Install aptitude using apt
      become: yes
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      become: yes
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools','redis-server']
    
    - name: Installing flask_restful
      pip: 
        name: flask-restful
    
    - name: Installing redis-py
      pip: 
        name: redis
    
    - name: Installing inotify
      pip: 
        name: inotify
       
    - name: Installing Flask
      pip: 
        name: Flask
    - name: Change file ownership, group and permissions
      file: dest=~/Server/apiserver.py mode=a+x
      

    - name: Start service flask, if not started
      become: yes
      systemd:
        name: flask
        state: started


        
